### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by johnfraney** [inkjet/pypostalcode#1]
Hello! Thanks for the great package. I've been having trouble getting it to work with Python 3.4 (I didn't try other 3.x versions):

```
Traceback (most recent call last):
  File "<string>", line 20, in <module
Complete output from command python setup.py egg_info:
Traceback (most recent call last):

  File "<string>", line 20, in <module

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hbzh40dv/pysqlite
```

I get that error when installing into a fresh Python 3.4 `virtualenv` but not a Python 2.7 `virtualenv`.

**Comment by inkjet** [comment]
This appears to be a problem with the pysqlite package not supporting Python 3:
1. https://github.com/ghaering/pysqlite/issues/72
2. http://stackoverflow.com/questions/23181197/install-pysqlite-in-virtualenv-with-python3-support

I've only used pypostalcode with Python 2.7 -- I should update the documentation to mention this.

**Comment by johnfraney** [comment]
Are there any features that require `pysqlite` rather than the built-in `sqlite3`? We could look into moving to `sqlite3` if not.

**Comment by inkjet** [comment]
Good idea. I updated `__init__.py` to remove the dependence on `pysqlite`.  

Before I push the updates to PyPi, could you copy the `pypostalcode` package to your `(virtualenv)/lib/python/site-packages` directory for testing?  The update worked for me with both Python 2.7 and 3.4, but I'd appreciate some independent verification.

**Comment by johnfraney** [comment]
I saw that `import.py` also had a reference to `pysqlite`, so I created PR #2 to get rid of that.

Edit: I also created PR #3 so that I could install from master using PIP to test it out before pushing to PyPi. It prevented me from installing in Python 3.4.

**Comment by inkjet** [comment]
Thanks!  I merged both of those in.

**Comment by johnfraney** [comment]
Okay, one last PR #4 , and that should do the trick. With that change it's working properly for me in both `python2.7` and `python3.4`. Thanks for getting this sorted out so quickly! I'll be using this in a project soon, and I'm happy for the Python3 compatibility.

**Comment by inkjet** [comment]
The changes have been folded into PyPi.  Thanks so much for your help and attention to detail.  I guess I should accept that 2.7 won't last forever... 

Let me know if `pip install` doesn't work for you in Python 2.7 or 3.4, and I'll reopen this.  Thanks again!

**Comment by johnfraney** [comment]
That did the trick! More and more Linux distros are shipping with Python3 by default, so I guess we'll have to make a total switch someday. Thanks again for the great package! It's exactly what I needed.
