### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by verhovsky** [inkjet/pypostalcode#8]
`pyzipcode` declared the license as "GPL" in `setup.py`:

https://github.com/inkjet/pypostalcode/blob/077c0085a57c2d24a0bb2596af56d701091fb9f4/setup.py#L16

But you declare the license as MIT in a `LICENSE.txt`:

https://github.com/inkjet/pypostalcode/blob/077c0085a57c2d24a0bb2596af56d701091fb9f4/LICENSE.txt

Is that allowed?

**Comment by inkjet** [comment]
Good catch! This should be as free as possible.

**Comment by inkjet** [comment]
Canada Post is protective of FSA info - here's their license saying it's free, but they can step in and prohibit our usage at any time: https://www.canadapost.ca/cpc/en/support/kb/sending/general-information/postal-code-targeting-terms-and-conditions

Any application using FSA info has to include the below disclaimer, which is in the README and you'll see used with Uber, Apple Maps, etc.:

"© This data includes information copied with permission from Canada Post Corporation."
